#! /bin/sh

# Based on:
#   https://kakyoism.github.io/2019/10/17/Build-a-GNU-Autotools-based-project-for-iOS-Part-1/
#
# Build for iOS 64bit-ARM variants and iOS Simulator
# - Place the script at project root
# - Customize MIN_IOS_VERSION and other flags as needed
#
# Test Environment
# - macOS 10.14.6
# - iOS 13.1
# - Xcode 11.1
#

# Target folder structure:
#  .
#  ├── _build
#  │   ├── libsodium
#  │   │   ├── platforms
#  │   │   │   ├── arm64
#  │   │   │   └── x86_64
#  │   │   └── universal
#  │   └── zeromq
#  │       └── platforms
#  │           ├── arm64
#  │           └── x86_64
#  └── universal            ('prefix' for zmq build)
#      ├── include
#      └── lib

# libsodium .a and .h *don't* need to appear in `built`

# Stop on errors
set -euo pipefail

# Print commands and expanded vars
set -x

# Library versions (used to fetch source tarballs)
SodiumVersion="1.0.18"
ZmqVersion="4.3.3"

# Common settings:
ScriptDir="$( cd "$( dirname "$0" )" && pwd )"

# Compiler options
OPT_FLAGS="-O3 -fembed-bitcode -fmodules"
MAKE_JOBS=8
MIN_IOS_VERSION=12.0

Build() {
    # Ensure -fembed-bitcode builds, as workaround for libtool macOS bug
    export MACOSX_DEPLOYMENT_TARGET="10.4"
    # Get the correct toolchain for target platforms
    export CC=$(xcrun --find --sdk "${SDK}" clang)
    export CXX=$(xcrun --find --sdk "${SDK}" clang++)
    export CPP=$(xcrun --find --sdk "${SDK}" cpp)
    export CFLAGS="${HOST_FLAGS} ${OPT_FLAGS}"
    export CXXFLAGS="${HOST_FLAGS} ${OPT_FLAGS}"
    export LDFLAGS="${HOST_FLAGS}"

    EXEC_PREFIX="${PLATFORMS}/${PLATFORM}"
    # --disable-shared to avoid Xcode loading dylibs even when staticlibs exist
    ./configure \
        --host="${CHOST}" \
        --prefix="${PREFIX}" \
        --exec-prefix="${EXEC_PREFIX}" \
        --enable-static \
        --disable-shared \
        $ADDITIONAL

    make clean
    mkdir -p "${PLATFORMS}" &> /dev/null
    make V=1 -j"${MAKE_JOBS}" --debug=j
    make install
}

GetZmq() {
    echo "Fetching zmq..."
    Tar="zeromq-${ZmqVersion}.tar.gz"
    Url="https://github.com/zeromq/libzmq/releases/download/v${ZmqVersion}/${Tar}"

    if [ ! -e "$Tar" ]
    then
        curl -L -O $Url
        tar xzf $Tar    
    else
        echo "Already had '$Tar'"
    fi
}

GetSodium() {
    echo "Fetching libSodium..."
    Tar="libsodium-${SodiumVersion}.tar.gz"
    
    if [ ! -e "$Tar" ]
    then
        curl -L -o "$Tar" https://github.com/jedisct1/libsodium/archive/${SodiumVersion}.tar.gz
        tar xzf "$Tar"
    else
        echo "Already had '$Tar'"
    fi
}

BuildPhone() {
    SDK="iphoneos"
    PLATFORM="device"
    PLATFORM_ARM=${PLATFORM}
    ARCH_FLAGS="-arch arm64 -arch arm64e"  # -arch armv7 -arch armv7s
    HOST_FLAGS="${ARCH_FLAGS} -miphoneos-version-min=${MIN_IOS_VERSION} -isysroot $(xcrun --sdk ${SDK} --show-sdk-path)"
    CHOST="arm-apple-darwin"
    Build
}

BuildSim() {
    SDK="iphonesimulator"
    PLATFORM="simulator"
    PLATFORM_ISIM=${PLATFORM}
    ARCH_FLAGS="-arch x86_64 -arch arm64e -arch arm64"
    HOST_FLAGS="${ARCH_FLAGS} -mios-simulator-version-min=${MIN_IOS_VERSION} -isysroot $(xcrun --sdk ${SDK} --show-sdk-path)"
    CHOST="x86_64-apple-darwin"
    Build
}

BuildUniversal() {
    cd "${PLATFORMS}/${PLATFORM_ARM}/lib"
    LIB_NAME=`find . -iname *.a`
    cd -
    mkdir -p "${UNIVERSAL}" &> /dev/null
    lipo -create -output "${UNIVERSAL}/${LIB_NAME}" \
        "${PLATFORMS}/${PLATFORM_ARM}/lib/${LIB_NAME}" \
        "${PLATFORMS}/${PLATFORM_ISIM}/lib/${LIB_NAME}"
}

BuildZmq() {
    GetZmq
    echo "Building ZMQ..."
    ZmqRoot="zeromq-${ZmqVersion}"
    PLATFORMS="${ScriptDir}/_build/${ZmqRoot}/_build/platforms"
    PREFIX="${ScriptDir}/universal"
    UNIVERSAL="${ScriptDir}/universal/lib"
    SodiumRoot="libsodium-${SodiumVersion}"
    ADDITIONAL="--with-libsodium=${ScriptDir}/_build/${SodiumRoot}/_build/universal"
    
    mkdir -p "$UNIVERSAL"
    cd "${ZmqRoot}"
    
    ./autogen.sh
    BuildPhone
    BuildSim
    # BuildUniversal
}

BuildSodium() {
    GetSodium
    echo "Building libSodium..."
    SodiumRoot="libsodium-${SodiumVersion}"
    PREFIX="${ScriptDir}/_build/${SodiumRoot}/_build"
    PLATFORMS="${PREFIX}/platforms"
    UNIVERSAL="${PREFIX}/universal"
    
    mkdir -p "$UNIVERSAL"
    
    cd "$SodiumRoot"
    ./autogen.sh
    ADDITIONAL=""
    BuildPhone
    BuildSim
    # BuildUniversal
}


mkdir -p "${ScriptDir}"/_build

cd "${ScriptDir}"/_build
# BuildSodium

cd "${ScriptDir}"/_build
BuildZmq

echo "Done! 😀"
